package com.vkyoungcn.learningtools.myrhythm;

public interface MyRhythmConstants {

    int REQUEST_CODE_RH_CREATE = 701;
    int RESULT_CODE_RH_CREATE_DONE = 702;
    int RESULT_CODE_RH_CREATE_FAILURE = 703;

    int DELIVER_ERROR = 799;

    int REQUEST_CODE_RH_EDIT = 711;
    int REQUEST_CODE_RH_OVERALL_EDIT = 712;

    int REQUEST_CODE_GP_EDIT = 721;
    int REQUEST_CODE_LY_EDIT = 729;
    int REQUEST_CODE_LYPH_EDIT = 728;



    int RESULT_CODE_RH_OVERALL_EDIT_DONE = 713;
    int RESULT_CODE_GP_EDIT_DONE = 722;
    int RESULT_CODE_LY_EDIT_DONE = 723;
    int RESULT_CODE_LYPH_EDIT_DONE = 724;
    int RESULT_CODE_RH_OVERALL_EDIT_CANCEL = 714;
    int RESULT_CODE_RH_PURE_EDIT_DONE = 715;
    int RESULT_CODE_GP_EDIT_CANCEL = 724;


    int REQUEST_CODE_LY_CREATE = 751;
    int REQUEST_CODE_LY_CREATE_FREE = 7511;
    int REQUEST_CODE_LY_CREATE_HL = 7512;
    int REQUEST_CODE_LY_CREATE_WL = 7513;

    int RESULT_CODE_LY_CREATED = 752;


    int REQUEST_CODE_GP_CREATE = 756;
    int RESULT_CODE_GP_CREATED = 757;

}
