package com.vkyoungcn.learningtools.myrhythm;

public interface MyRhythmConstants {

    int REQUEST_CODE_RH_CREATE = 701;
    int RESULT_CODE_RH_CREATE_DONE = 702;
    int RESULT_CODE_RH_CREATE_FAILURE = 703;


    int REQUEST_CODE_RH_EDIT = 711;
    int REQUEST_CODE_RH_OVERALL_EDIT = 712;

    int REQUEST_CODE_GP_EDIT = 721;
    int REQUEST_CODE_LY_EDIT = 729;



    int RESULT_CODE_RH_OVERALL_EDIT_DONE = 713;
    int RESULT_CODE_GP_EDIT_DONE = 722;
    int RESULT_CODE_LY_EDIT_DONE = 723;
    int RESULT_CODE_RH_OVERALL_EDIT_CANCEL = 714;
    int RESULT_CODE_RH_PURE_EDIT_DONE = 715;
    int RESULT_CODE_GP_EDIT_CANCEL = 724;

}
